import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";

import { parseChecksums, verifyDownload } from "../src/verify";

function fileWith(contents: string): { path: string; sha256: string } {
  const dir = mkdtempSync(join(tmpdir(), "noetive-verify-"));
  const path = join(dir, "noetive-mcp");
  writeFileSync(path, contents);
  return { path, sha256: createHash("sha256").update(contents).digest("hex") };
}

test("a matching checksum passes", () => {
  const { path, sha256 } = fileWith("binary bytes");

  verifyDownload(path, "noetive-mcp-linux-x64", `${sha256}  noetive-mcp-linux-x64\n`);
});

// A tampered or truncated download must never become executable. This is the
// whole reason the fallback path is allowed to exist at all.
test("a mismatched checksum is refused and says why", () => {
  const { path } = fileWith("binary bytes");
  const wrong = "0".repeat(64);

  assert.throws(
    () => verifyDownload(path, "noetive-mcp-linux-x64", `${wrong}  noetive-mcp-linux-x64\n`),
    /checksum mismatch/,
  );
});

// An unlisted asset is a failure, not a pass. Treating "no checksum published"
// as acceptable makes the check bypassable by exactly the party who can also
// serve a malicious download.
test("an asset with no published checksum is refused", () => {
  const { path, sha256 } = fileWith("binary bytes");

  assert.throws(
    () => verifyDownload(path, "noetive-mcp-linux-x64", `${sha256}  some-other-asset\n`),
    /no published checksum/,
  );
});

// Release files carry blank lines and occasionally a header; a strict parse
// would turn a cosmetic difference into a failed install.
test("checksum parsing tolerates blank lines, headers and binary markers", () => {
  const sums = parseChecksums(
    ["# generated by goreleaser", "", "a".repeat(64) + "  noetive-mcp-linux-x64", "b".repeat(64) + " *noetive-mcp-win32-x64.exe", ""].join("\n"),
  );

  assert.equal(sums.get("noetive-mcp-linux-x64"), "a".repeat(64));
  assert.equal(sums.get("noetive-mcp-win32-x64.exe"), "b".repeat(64));
});
